### ISSUE TITLE
"Lock on package COMMON-LISP violated" on versions above 0.1 with SBCL

### ISSUE THREAD

**Issue by Drainful** [alex-gutev/generic-cl#1]
I get the following error

> Lock on package COMMON-LISP violated when setting the compiler-macro-function of MAKE-LOAD-FORM while in package GENERIC-CL.IMPL.

when running `(ql:quickload :generic-cl) ` with versions of generic-cl 0.2 or higher.

Steps to reproduce:
- cd to ~/quicklisp/local-projects/
- clone https://github.com/alex-gutev/generic-cl/
- git checkout tags/v0.2.1 (or v0.2)
- open sbcl and run (ql:quickload :generic-cl)

The problem can be resolved by selecting a restart, but the consequences are undefined according to the standard. Is this intentional behavior, and if so, which restart do you recommend be used?

**Comment by alex-gutev** [comment]
This is a bug in [static-dispatch](https://github.com/alex-gutev/static-dispatch) which was fixed in [v0.2.3](https://github.com/alex-gutev/static-dispatch/releases/tag/v0.2.3). You need to clone v0.2.3 of static-dispatch and load it instead of the version currently in quicklisp.

**Comment by Drainful** [comment]
Thank you. Sorry for bothering you. Closing.
