### ISSUE TITLE
Defining "get" and "setf-get" on more objects?

### ISSUE THREAD

**Issue by anlsh** [alex-gutev/generic-cl#2]
Are there any reasons for not defining `get` and corresponding `setf` expanders for other objects? Arrays are the omission I miss most, but it might make sense to provide implementations for lists (treating the key as an integer index) and *maybe* even slots (like [access](https://github.com/AccelerationNet/access) does).

I can work on this if we're open to it.

**Comment by alex-gutev** [comment]
The function `get` retrieves an element from a _map_ by _key_. Most commonly a _map_ is either `hash-map` or a standard `hash-table`, however an `ALIST` or `PLIST` can also be used as a _map_. The `get` function already contains a method, specialized on lists, which treats the list as an `ALIST` or `PLIST`, depending on the whether the first element is a `CONS`, and retrieves the element with the given key.

The [`generic-cl:elt`](https://alex-gutev.github.io/generic-cl/#elt) function performs the function you're looking for, retrieving an element from a sequence by index and it has methods which work on both lists and arrays. However, it doesn't have a method specialized for `HASH-MAPS`'s, which allows you to retrieve a map element by key.

If having a unified interface for retrieving a sequence element by index and by key is important, an `elt` method specialized on `hash-maps` can be added which simply treats its `index` argument as a key and retrieves the value of the map entry corresponding to the key.
