### ISSUE TITLE
Don't depend on cl-arrows

### ISSUE THREAD

**Issue by Ambrevar** [alex-gutev/generic-cl#5]
cl-arrows is abandoned and worse of all, has no license, which effectively makes all dependencies non-free software :(

https://github.com/nightfly19/cl-arrows/issues/5

https://gitlab.com/Harleqin/arrows.git can be used as a drop in replacement for static-dispatch dispatch at least, but there may be more work involved for generic-cl.

**Comment by Ambrevar** [comment]
There is also https://github.com/hipeta/arrow-macros.

**Comment by alex-gutev** [comment]
Fixed in commit 196d990e34d06e37189918502602e5e71af67abf. Thanks for pointing this issue out.

**Comment by Ambrevar** [comment]
Thanks!
