### ISSUE TITLE
cl-arrows is proprietary software

### ISSUE THREAD

**Issue by phoe** [alex-gutev/generic-cl#8]
cl-arrows [does not have a license file](https://github.com/nightfly19/cl-arrows/issues/5) which makes it proprietary software.

Consider switching to another arrow macro library, such as [arrows](https://github.com/Harleqin/arrows), [arrow-macros](https://github.com/hipeta/arrow-macros), or (shameless plug) [binding-arrows](https://github.com/phoe/binding-arrows).

**Comment by alex-gutev** [comment]
Duplicate of #5

**Comment by phoe** [comment]
Woop - sorry about that. The changes have not yet been pulled into Quicklisp so I operated on stale data.
